### ISSUE TITLE
behavior.js

### ISSUE THREAD

**Issue by hockinsk** [benardt/JScad2d#1]
Hi Bernard, I am interested in your JScad2d project. I notice behavior.js is missing though, so I can't get it to work. Can you help?

Kind regards

Sam

**Comment by benardt** [comment]
Hi,

I am currently in business trip with limited access to my emails. I try to
do something for you by tomorrow.

BR,
--
Thierry

**Comment by hockinsk** [comment]
Hi Thierry,

Many thanks. No problem.

Kind regards

Sam

**Comment by hockinsk** [comment]
Hi Thierry,

Could you help me with the behavior.js file if convenient?

Regards

Sam

**Comment by benardt** [comment]
Hi Sam,

I just checked my project. "behavior.js" do not exist any more. It is an
old js file replaced by JScad2d.js.

I hope this will help.

Regards,
--
Thierry

2017-01-26 20:49 GMT+01:00 hockinsk <notifications@github.com>:

> Hi Thierry,
>
> Could you help me with the behavior.js file if convenient?
>
> Regards
>
> Sam
>
>
