### ISSUE TITLE
how to get it to work?

### ISSUE THREAD

**Issue by tekknow** [benardt/JScad2d#5]
I downloaded project and launched index.htm.  I loaded file from examples folder.  When I click Example button it says "This site says... Already exist!"  If I click the Debug button a new window pops up that says "Drawing not loaded".  What am I missing?

**Comment by benardt** [comment]
Hello,

Thanks to evaluate JScad2d.

What is your internet browser (name and version)? Normally work fine with
Firefox and Chrome.

Have a nice day,
--
TB

2018-02-14 1:33 GMT+01:00 tekknow <notifications@github.com>:

**Comment by tekknow** [comment]
Google Chrome is up to date
Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by benardt** [comment]
Do you authorize popup window? To allow to draw big part with double screen computer (more comfortable), we use popup to have drawing in one window in one screen and ui in anther window in another screen.

If by clicking Example button, site says "Already exists!" then the part is already loaded. Try browser refresh button to start with no part.

I continue to investigate...

Have a nice day,

TB

**Comment by tekknow** [comment]
It is working now after I figured out how to allow popups.  But the dimension values are so tiny they cannot be read unless you zoom way in.  Is there a way to make the dimension text stay the same size regardless of the zoom level?

**Comment by benardt** [comment]
Sorry, this functionality is not coded. We have to discuss internally to keep or not this new functionality.

For the time being, it is possible to change font size inside Format option:
```
V Format
          font_size: 12
```

Change 12 by other value (24 for instance) to increase the font size.
